name: webview_translator
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.15
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
flutter:
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  assets:
    - assets/
